formatter: "markdown table" # this is required

version: "~> 0.19.0"

header-from: "docs/.header.md"
footer-from: "docs/.footer.md"

recursive:
  enabled: false

sections:
  hide: [providers]
  show: []

content: ""

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  default: true # show “Default” value as column
  escape: true
  hide-empty: true
  html: false
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
